name: big-bear-adguard-home-host
services:
    big-bear-adguard-home-host:
        container_name: big-bear-adguard-home-host
        image: adguard/adguardhome:v0.107.73
        labels:
            icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
        network_mode: host
        restart: unless-stopped
        volumes:
            - type: bind
              source: /DATA/AppData/$AppID/data/work
              target: /opt/adguardhome/work
              bind:
                create_host_path: true
            - type: bind
              source: /DATA/AppData/$AppID/data/conf
              target: /opt/adguardhome/conf
              bind:
                create_host_path: true
        x-casaos:
            volumes:
                - container: /opt/adguardhome/work
                  description:
                    en_us: 'Container Path: /opt/adguardhome/work'
                - container: /opt/adguardhome/conf
                  description:
                    en_us: 'Container Path: /opt/adguardhome/conf'
networks:
    default:
        name: big-bear-adguard-home-host_default
x-casaos:
    architectures:
        - amd64
        - arm64
    author: BigBearTechWorld
    category: BigBearCasaOS
    description:
        en_us: Use if you're going to use Adguard Home as a DHCP server. AdGuard Home is a network-wide software for blocking ads and tracking. After you set it up, it'll cover all your home devices, and you won't need any client-side software for that. Learn more on our official Github repository.
    developer: AdGuardTeam
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/adguard-home.png
    is_uncontrolled: false
    main: big-bear-adguard-home-host
    port_map: "80"
    screenshot_link:
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-1.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-2.png
        - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/screenshot-3.png
    store_app_id: big-bear-adguard-home-host
    tagline:
        en_us: Network Mode is host. Network-wide ads & trackers blocking DNS server.
    thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/AdGuardHome/thumbnail.png
    tips:
        before_install:
            en_us: |
                Run this script:

                ```
                bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/generate-adguard-home-config/run.sh)"
                ```

                After running this script, you need to restart the container.
    title:
        en_us: AdGuard Home (HOST)
